normalname:
    - "DNA64926"
normalfastqs:
    - "/seqstore/instruments/novaseq_687_gc/Demultiplexdir/200327_A00687_0067_AH5V2HDSXY/KG/DNA64926"
tumorname:
    - "DNA64925"
tumorfastqs:
    - "/seqstore/instruments/novaseq_687_gc/Demultiplexdir/200327_A00687_0067_AH5V2HDSXY/KG/DNA64925"
igvuser:
    - "barncancer"
