normalname:
    - "WNB149N"
normalfastqs:
    - "/seqstore/instruments/novaseq_687_gc/Demultiplexdir/200421_A00687_0073_BH522WDSXY/G20-004/WNB149N"
tumorname:
    - "WNB149AT"
tumorfastqs:
    - "/seqstore/instruments/novaseq_687_gc/Demultiplexdir/200421_A00687_0073_BH522WDSXY/G20-004/WNB149AT"
igvuser:
    - "susanne.fransson"
ivauser:
    - "SusanneF"
