normalname:
    - "P11865_144"
normalfastqs:
    - "/seqstore/webfolders/wgs/researchproject/fogelstrand/re_analysis/fastqlinks/P11865_144"
tumorname:
    - "P11865_143"
tumorfastqs:
    - "/seqstore/webfolders/wgs/researchproject/fogelstrand/re_analysis/fastqlinks/P11865_143"
igvuser:
    - "anna.staffas"
ivauser:
    - ""
