---
novaseq_687_gc:
  root_path: "/seqstore/novaseq_687_gc/"
  demultiplex_path: "/seqstore/novaseq_687_gc/Demultiplexdir/"
  seq_name_regex: '^[0-9]{6}_A00687_[0-9]{4}_.{10}(?:\+.{8})?$'

novaseq_A01736:
  root_path: "/seqstore/novaseq_A01736/"
  demultiplex_path: "/seqstore/novaseq_A01736/Demultiplexdir/"
  seq_name_regex: '^[0-9]{6}_A01736_[0-9]{4}_.{10}(?:\+.{8})?$'

previous_runs_file_path: '../runlists/novaseq_runlist.txt'
wrapper_log_path: '/clinical/exec/wgs_somatic/logs'

hg38ref:
  GMS-BT: 'yes'
  GMS-AL: 'yes'

workingdir: '/clinical/data/wgs_somatic/cron'

#hcp_download_dir: '/medstore/results/wgs/tmp/hcp_downloads'
hcp_download_dir: '/medstore/projects/P23-075/wgs_somatic/hcp_downloads'

hcp:
  qsub_script: 'tools/hcp_download_fq.sh'
  queue: 'routine.q'
  threads: 20
  credentials: '/medstore/credentials/gmc-west_legacy_credentials.json'
  peta_script: 'tools/run_petasuite.sh'
  spring_script: 'tools/run_spring.sh' 
