---
novaseq_687_gc:
  root_path: "/seqstore/novaseq_687_gc/"
  demultiplex_path: "/seqstore/novaseq_687_gc/Demultiplexdir/"
  seq_name_regex: '^[0-9]{6}_A00687_[0-9]{4}_.{10}(?:\+.{8})?$'

novaseq_A01736:
  root_path: "/seqstore/novaseq_A01736/"
  demultiplex_path: "/seqstore/novaseq_A01736/Demultiplexdir/"
  seq_name_regex: '^[0-9]{6}_A01736_[0-9]{4}_.{10}(?:\+.{8})?$'

previous_runs_file_path: '../runlists/novaseq_runlist.txt'
wrapper_log_path: '/clinical/exec/wgs_somatic/logs'

hg38ref:
  GMS-BT: 'yes'
  GMS-AL: 'yes'

cron_outpath: '/clinical/data/wgs_somatic/cron'

manual_outpath: '/clinical/data/wgs_somatic/manual/'

hcp_download_dir: '/clinical/data/wgs_somatic/hcp_downloads'

hcp:
  download_script: 'tools/hcp_download.py'
  queue: 'routine.q'
  threads: 20
  credentials_file: '/clinical/exec/wgs_somatic/dependencies/credentials/gmc-legacy_credentials.json'
  bucket: 'data'  # bucket to default to if not found in slims
  peta_script: 'tools/run_petasuite.sh'
  spring_script: 'tools/run_spring.sh' 
