---
novaseq:
  root_path: "/seqstore/instruments/novaseq_687_gc/"
  demultiplex_path: "/seqstore/instruments/novaseq_687_gc/Demultiplexdir/"

previous_runs_file_path: 'novaseq_runlist.txt'

#igv:
#  root_path: '/seqstore/webfolders/igv/data/'
#  GMS-BT: 'barncancer_hg38'
#  GMS-AL: 'barncancer_hg38'
#  G21-004: 'susanne.fransson'

