---
novaseq_687_gc:
  root_path: "/seqstore/novaseq_687_gc/"
  demultiplex_path: "/seqstore/novaseq_687_gc/Demultiplexdir/"
  seq_name_regex: '^[0-9]{6}_A00687_[0-9]{4}_.{10}(?:\+.{8})?$'

novaseq_A01736:
  root_path: "/seqstore/novaseq_A01736/"
  demultiplex_path: "/seqstore/novaseq_A01736/Demultiplexdir/"
  seq_name_regex: '^[0-9]{6}_A01736_[0-9]{4}_.{10}(?:\+.{8})?$'

novaseqx_LH01216:
  root_path: "/seqstore/novaseqx_LH01216/"
  demultiplex_path: "/seqstore/novaseqx_LH01216/Demultiplexdir/"
  seq_name_regex: '^[0-9]{8}_LH01216_[0-9]{4}_.{10}(?:\+.{8})?$'

previous_runs_file_path: '../runlists/novaseq_runlist.txt'
wrapper_log_path: '/clinical/exec/wgs_somatic/logs'

cron_outpath: '/clinical/data/wgs_somatic/cron'

manual_outpath: '/clinical/data/wgs_somatic/manual/'

hcp_download_dir: '/clinical/data/wgs_somatic/hcp_downloads'

hcp:
  download_script: 'tools/hcp_download.py'
  download_locations:
    sg1_illumina:
      bucket: 'illumina'
      credentials_file: '/clinical/exec/wgs_somatic/dependencies/credentials/sg1.json'
    sg1_data:
      bucket: 'data'
      credentials_file: '/clinical/exec/wgs_somatic/dependencies/credentials/sg1.json'
    hcp_data:
      bucket: 'data'
      credentials_file: '/clinical/exec/wgs_somatic/dependencies/credentials/gmc-legacy_credentials.json'
  queue: 'routine.q'
  threads: 20
  peta_script: 'tools/run_petasuite.sh'
  spring_script: 'tools/run_spring.sh' 
  connect_timeout: 10  # Optional arguments for hcp_download.py
  read_timeout: 30
  retries: 20

slims_credentials_path: '/clinical/exec/wgs_somatic/dependencies/credentials/slims_credentials.yaml'

email_config_path: '/clinical/exec/wgs_somatic/dependencies/configs/mail_config.yaml'

develop_mode:
  outpath: '/clinical/dev/cgg-cancer/wgs_somatic/data/' 
  runpath: '/clinical/dev/cgg-cancer/wgs_somatic/810806_A000000_0000_FL00OWCELL+1a2b3c4d'
  log_path: '/clinical/dev/cgg-cancer/wgs_somatic/logs/'
  email_config_path: '/clinical/dev/cgg-cancer/wgs_somatic/dependencies/configs/mail_config.yaml'
  fail:
    samples:
      - sample: 'DNA96714_221028_BH2CGFDSX5'
        type: 'normal'
        fastq_paths: ['/clinical/data/wgs_somatic/testfiles/221028_BH2CGFDSX5/DNA96714_221028_BH2CGFDSX5_S15_R1_001.fastq.gz', '/clinical/data/wgs_somatic/testfiles/221028_BH2CGFDSX5/DNA96714_221028_BH2CGFDSX5_S15_R2_001.fastq.gz']
      - sample: 'DNA97155_221104_AH3L7JDSX5'
        type: 'tumor' 
        fastq_paths: ['/clinical/data/wgs_somatic/testfiles/221104_AH3L7JDSX5/DNA97155_221104_AH3L7JDSX5_S4_R1_001.fastq.gz', '/clinical/data/wgs_somatic/testfiles/221104_AH3L7JDSX5/DNA97155_221104_AH3L7JDSX5_S4_R1_001.fastq.gz']

